# Using https://www.circuitstate.com/pinouts/doit-esp32-devkit-v1-wifi-development-board-pinout-diagram-and-reference
esphome:
  name: smoker-esphome
  friendly_name: Smoker
  project:
    name: daedalus-labs.smoker
    version: "0.1.0"

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

# Configuration variables
substitutions:
  display_name: "Smoker Controller"
  wifi_update_time: 60s
  temperature_update_time: 30s

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret smoker_api_key

safe_mode:

ota:
  platform: esphome
  password: !secret smoker_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${display_name}"
    password: !secret fallback_ap_password

captive_portal:

web_server:
  port: 80

spi:
  - id: vspi
    clk_pin: 18
    miso_pin: 19
    mosi_pin: 23
    interface: spi3
  - id: hspi
    clk_pin: 14
    miso_pin: 12
    mosi_pin: 13
    interface: spi2

sensor:
  - platform: max6675
    id: interior_temp
    icon: "mdi:grill"
    name: "Smoker Interior Temperature"
    cs_pin: GPIO5
    spi_id: vspi
    update_interval: ${temperature_update_time}

  - platform: max6675
    id: food_temp
    icon: "mdi:temperature"
    name: "Food Temperature"
    cs_pin: GPIO15
    spi_id: hspi
    update_interval: ${temperature_update_time}

  # Uptime sensor
  - platform: uptime
    name: Uptime
    id: uptime_sensor

  # Wifi Signal
  - platform: wifi_signal
    name: "Wifi Signal dB"
    id: wifi_signal_db
    update_interval: ${wifi_update_time}
    entity_category: "diagnostic"

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

  # Climate sensor for the Smoker
  - platform: dht
    pin: 25
    model: DHT22
    temperature:
      name: "Exterior Temperature"
      id: case_temperature
      filters:
        - sliding_window_moving_average:
            window_size: 8
            send_every: 4
            send_first_at: 4
    humidity:
      name: "Exterior Humidity"
      id: case_humidity
      filters:
        - sliding_window_moving_average:
            window_size: 8
            send_every: 4
            send_first_at: 4
    update_interval: ${temperature_update_time}

output:
  # Activity LED
  - platform: gpio
    pin:
      number: 2
      mode: output
    id: activity_led
  - platform: ledc
    pin: GPIO26
    frequency: 10000 Hz
    id: smoker_fan_pwm

fan:
  - platform: speed
    id: smoker_fan
    name: "Smoker Fan"
    output: smoker_fan_pwm
    on_turn_on: 
      then:
        - output.turn_on: activity_led
    on_turn_off: 
      then:
        - output.turn_off: activity_led

switch:
  - platform: restart
    name: ${display_name} Restart

time:
  - platform: homeassistant
    id: homeassistant_time

number:
  - platform: template
    name: "Target Smoker Temperature"
    id: target_interior_temp
    icon: "mdi:grill"
    device_class: temperature
    min_value: 0
    max_value: 500
    step: 1
    optimistic: true

  - platform: template
    name: "Target Food Temperature"
    id: target_food_temp
    icon: "mdi:temperature-alert"
    device_class: temperature
    min_value: 0
    max_value: 500
    step: 1
    optimistic: true
