esphome:
  name: water-meter-esp32
  friendly_name: Water Meter

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

safe_mode:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP32 Water Meter"
    password: !secret fallback_ap_password

captive_portal:

output:
  # Activity LED
  - platform: gpio
    pin:
      number: 2
      mode: output
    id: activity_led
 
sensor:
  # Climate sensor for the Water Meter
  - platform: dht
    pin: 25
    model: DHT22
    temperature:
      name: "Water Meter Temperature"
      id: water_meter_temperature
      filters:
        - sliding_window_moving_average:
            window_size: 8
            send_every: 4
            send_first_at: 4
    humidity:
      name: "Water Meter Humidity"
      id: water_meter_humidity
      filters:
        - sliding_window_moving_average:
            window_size: 8
            send_every: 4
            send_first_at: 4
    update_interval: 30s

  # Uptime sensor
  - platform: uptime
    name: Uptime
    id: uptime_sensor

  # Pulse counter
  - platform: pulse_counter
    pin:
      number: 13
      inverted: true
      mode:
        input: true
        pullup: true
    update_interval : 6s
    name: "water pulse"
    id: water_pulse

  # # Pulse "meter"
  # - platform: pulse_meter
  #   pin: 
  #     number: 13
  #     inverted: true
  #     mode:
  #       input: true
  #       pullup: true
  #   name: "Water Pulse Meter"
  #   unit_of_measurement: "ccf/min"
  #   icon: "mdi:water"
  #   total:
  #     name: "Water Total"
  #     unit_of_measurement: "ccf"

  # - platform: pulse_meter
  #   pin: 
  #       number: 13
  #       inverted: true
  #       mode:
  #         input: true
  #         pullup: true
  #   name: "Water Pulse Meter"
  #   unit_of_measurement: "ccf/min"
  #   icon: "mdi:water"
  #   total:
  #     name: "Water Meter Total"
  #     unit_of_measurement: "ccf"
  #     id: water_meter_total
  #     accuracy_decimals: 3
  #     device_class: water
  #     state_class: total_increasing
  #     filters:
  #       - multiply: 0.001

  - platform: template
    name: "Water Usage Liter"
    id: water_flow_rate
    accuracy_decimals: 1
    unit_of_measurement: "ccf/min"
    icon: "mdi:water"
    lambda: return (id(water_pulse).state * 10);
    update_interval: 6s

# api:
#   actions:
#     - action: set_pulse_total
#       variables:
#         new_pulse_total: int
#       then:
#         - water_pulse.set_total_pulses:
#             id: water_pulse
#             value: !lambda 'return new_pulse_total;'

time:
  - platform: homeassistant
    id: homeassistant_time
